### ISSUE TITLE
Issue in Server Assignment

### ISSUE THREAD

**Issue by gosh24** [atlarge-research/cn-lab-student#10]
Couldn't create a pull request as nothing to edit here.

In this [link](https://computer-networks-lab.gitbook.io/computer-networks-lab-manual/assignments/a3-chat-server-250-points), it is advised that PR4: If a user logs in with an invalid username, the server must send a BAD-RQST-BODY message in response. However, the code actually looks for BAD-RQST-HDR, or at least this is how it is in CodeGrade. Actually sending BAD-RQST-BODY results in the printout of "Successful login" message.

Also, just to point out, there are quite a few grammatical mistakes in the chat client assignment. For example, "Welcome to chat client. Enter you(r) <--- login:". In codegrade this was fixed, but in the local test environment, it wasn't, which caused testing issues. I have not checked since, so please accept my apologies if the issue has been resolved.

Not sure if it this issue counts, but if it does - gbv500.

**Comment by gosh24** [comment]
Another issue:

The last test "Server responds with a bad header if the message sent by the client who is not logged in" seems invalid to me.

My server checks if the user has disallowed characters such as spaces, commas etc. and sends a BAD-RQST-HDR (what is actually required). However, the issue is that the test expects "Error: Unknown issue in previous message header." but the client checks for disallowed characters and prevents further action. I suppose that the code in the jar file actually does not get to the point where it prints/listens for the server so that it can handle the BAD-RQST-HDR.

Please check.

**Comment by FBastiaan04** [comment]
> Another issue:
> 
> The last test "Server responds with a bad header if the message sent by the client who is not logged in" seems invalid to me.
> 
> My server checks if the user has disallowed characters such as spaces, commas etc. and sends a BAD-RQST-HDR (what is actually required). However, the issue is that the test expects "Error: Unknown issue in previous message header." but the client checks for disallowed characters and prevents further action. I suppose that the code in the jar file actually does not get to the point where it prints/listens for the server so that it can handle the BAD-RQST-HDR.
> 
> Please check.

I submitted a [different issue](https://github.com/atlarge-research/cn-lab-student/issues/12) for that part which has been solved.

**Comment by Vlad2000Andrei** [comment]
Thanks @gosh24, typose (and the part also mentioned by @FBastiaan04 ) should be fixed. You can check locally by pulling the latest docker image `docker run --rm --network="host" --pull=always -v $(pwd):/home/compnet/student -it ghcr.io/atlarge-research/cn-lab-student:latest` (replace `$(pwd)` with `${PWD}` for Windows PowerShell). Please let me know if that's not the case!
