### ISSUE TITLE
server_check/ChatClient.jar cannot send a newline character as the username, since it sees the newline as the end of input

### ISSUE THREAD

**Issue by FBastiaan04** [atlarge-research/cn-lab-student#11]
server_check/ChatClient.jar cannot send a newline character as the username, since it sees the newline as the end of input. This is fine for actual use, but it means test 011 is impossible. This was "fixed" by using "\\n" in check.py. However, this is a perfectly legal username, since it contains no newline character. Only a literal backslash and a literal n. Not a newline character. I would love to do a pull request, but that is a bit too challenging with a .jar file.

fba257

**Comment by FBastiaan04** [comment]
You could maybe have the java code replace a certain string (let's say \\) with a newline. Then the check.py would have to insert \\ instead of \n in the test

**Comment by Vlad2000Andrei** [comment]
Hi @FBastiaan04, you're completely right! Thank you for catching it, fixed (among other things in #21 ) and `+50` awarded in Canvas. In the future, when finding a bug, please mention your VUnet ID so we can award you the points you deserve (found you by name this time).
