### ISSUE TITLE
server_check/ChatClient.jar has another error, it cannot do anything before logging in

### ISSUE THREAD

**Issue by FBastiaan04** [atlarge-research/cn-lab-student#12]
This would be fine for real use, but it makes test 016 impossible. Any text that is entered before logging in, even if it starts with an @ or !, is processed as a username, meaning it will print "Cannot log in as !who. That username contains disallowed characters." instead of "Error: Unknown issue in previous message header.". Again, error in jar file, cannot submit pull request

fba257

**Comment by fzovpec** [comment]
Hi, there! I would like to inform you that we have tracked an error down and submitted a fix. Thank you for informing us of an error. Your error description has hinted to us an error solution, and therefore we have decided to award you with 50 points! As a final note, congratulations on finding a bug in an extra assignment even before the first lecture!
