### ISSUE TITLE
[Chat Server] Problems ChatClient.jar

### ISSUE THREAD

**Issue by Stefan9110** [atlarge-research/cn-lab-student#36]
# Description

There seems to be an implementation problem with the `ChatClient.jar` file that makes some checks fail even though the server was implemented properly.

# Problems

## 1. Handling invalid usernames
On Canvas, the following is specified:
> **PR4**: If a user logs in with an invalid username, the server must send a BAD-RQST-BODY message in response.

Upon decompiling `ChatClient.jar`, the following line (at line 40) of code is observed when handling invalid usernames:

```java
// ...
               } else {
                  if (!var3.startsWith("BAD-RQST-HDR")) {
                      // ...
                  }

                  System.out.println("Error: Unknown issue in previous message header.");
               }
```

The problem is that the client is expecting a `BAD-RQST-HDR` instead of `BAD-RQST-BODY` in case of invalid characters, as specified by the assignment. This makes the tests `chat_server_0010`, `chat_server_0011`, `chat_server_0012` fail.

## 2. `LIST-OK` commas

On Canvas, the following is specified:

> **PR9**: The body of the `LIST-OK` message must be a comma-separated list, containing only exactly the usernames of all currently logged-in user

Upon decompiling `ChatClient.jar`, the following lines (at line 108) of code is observed when handling the `LIST-OK` response:

```java
               } else if (var2.startsWith("LIST-OK")) {
                  var3 = var2.split(" ");
```
Instead of _splitting_ by a `,` character, it is instead separating by spaces. This makes the test `chat_server_004` fail.

## 3. Testing sending a message before login

The code for the check `chat_server_016` is:

```py
def send_message_before_login():
    client_process, output_buffer = start_script()
    client_name_1 = generate_name()

    expected_output = "Error: Unknown issue in previous message header."
    client_process.sendline(f'@{client_name_1} {generate_message(16, 32)}')

    handle_pexpect(client_process, [client_process], expected_output, output_buffer, "sending a message before logging in")

    client_process.terminate()

    return client_process, output_buffer
```
However, the `ChatClient.jar` used for testing implements the following check before logging in:
```java
               } else if (containsSpecialCharacters(var2)) {
                  System.out.println("Cannot log in as " + var2 + ". That username contains disallowed characters.");
                  continue;
               }
```

Therefore, the test tries to send a message such as `@name message` before logging in, but the client prevents that, as the client recognizes `@` as a disallowed character. The message sent by the check is interpreted by the client as a login username, not passing this line of code. In other words, the client prevents this _edge-case test_ from being tested.

# Fixes
I would be glad to fix all of these issues if I were given access to the source code for the `ChatClient.jar` project. I am not about to make changes to a decompiled codebase. 

You can contact me privately or through my VU id `vu\dha242`.

**Comment by fzovpec** [comment]
Dear Daniel,

To quickly come back to you, I am currently investigating issue 2 which seems to be an issue but issues 1 and 3 have already been, as far as I know, fixed. Could you please make sure that you have the latest test version (by pulling them from the docker as it is specified in the README)?

**Comment by fzovpec** [comment]
Hey, there! You were right about the chat client. Thanks a lot for your careful analysis of the protocol A requirement and further investigation into the test code. Great job! Fix: https://github.com/atlarge-research/cn-lab-student/commit/70e3540c33230e4e032bf7960336cc87c7f61d9c
